title: Tutorials and Exercises
description: Digital Humanities Stuff
theme: just-the-docs

url: https://susannalles.github.io/tutorials/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
